package com.example.foodplanner.Model;

public class Converter {
    public static MealPojoPlan convertToMealPojoPlan(MealPojo mealPojo, String date) {
        return new MealPojoPlan(
                mealPojo.getIdMeal(),
                mealPojo.getStrMeal(),
                mealPojo.getStrCategory(),
                mealPojo.getStrInstructions(),
                mealPojo.getStrMealThumb(),
                mealPojo.getStrYoutube(),
                mealPojo.getStrIngredient1(),
                mealPojo.getStrIngredient2(),
                mealPojo.getStrIngredient3(),
                mealPojo.getStrIngredient4(),
                mealPojo.getStrIngredient5(),
                mealPojo.getStrIngredient6(),
                mealPojo.getStrIngredient7(),
                mealPojo.getStrIngredient8(),
                mealPojo.getStrIngredient9(),
                mealPojo.getStrIngredient10(),
                mealPojo.getStrIngredient11(),
                mealPojo.getStrIngredient12(),
                mealPojo.getStrIngredient13(),
                mealPojo.getStrIngredient14(),
                mealPojo.getStrIngredient15(),
                mealPojo.getStrIngredient16(),
                mealPojo.getStrIngredient17(),
                mealPojo.getStrIngredient18(),
                mealPojo.getStrIngredient19(),
                mealPojo.getStrIngredient20(),
                mealPojo.getStrMeasure1(),
                mealPojo.getStrMeasure2(),
                mealPojo.getStrMeasure3(),
                mealPojo.getStrMeasure4(),
                mealPojo.getStrMeasure5(),
                mealPojo.getStrMeasure6(),
                mealPojo.getStrMeasure7(),
                mealPojo.getStrMeasure8(),
                mealPojo.getStrMeasure9(),
                mealPojo.getStrMeasure10(),
                mealPojo.getStrMeasure11(),
                mealPojo.getStrMeasure12(),
                mealPojo.getStrMeasure13(),
                mealPojo.getStrMeasure14(),
                mealPojo.getStrMeasure15(),
                mealPojo.getStrMeasure16(),
                mealPojo.getStrMeasure17(),
                mealPojo.getStrMeasure18(),
                mealPojo.getStrMeasure19(),
                mealPojo.getStrMeasure20(),
                mealPojo.getStrSource(),
                date);
    }
}
